//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright YEAR The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1beta1

import (
	"context"
	"fmt"
	kcp "github.com/kcp-dev/apimachinery/pkg/client"
	"github.com/kcp-dev/logicalcluster"
	authenticationapiv1beta1 "k8s.io/api/authentication/v1beta1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	authenticationv1beta1 "k8s.io/client-go/kubernetes/typed/authentication/v1beta1"
	"k8s.io/client-go/rest"
)

// WrappedAuthenticationV1beta1 wraps the client interface with a
// logical cluster.
type WrappedAuthenticationV1beta1 struct {
	cluster  logicalcluster.Name
	delegate authenticationv1beta1.AuthenticationV1beta1Interface
}

// New creates a WrappedAuthenticationV1beta1 with the given logical cluster and client interface.
func New(cluster logicalcluster.Name, delegate authenticationv1beta1.AuthenticationV1beta1Interface) *WrappedAuthenticationV1beta1 {
	return &WrappedAuthenticationV1beta1{cluster: cluster, delegate: delegate}
}

// RESTClient returns the underlying RESTClient.
func (w *WrappedAuthenticationV1beta1) RESTClient() rest.Interface {
	return w.delegate.RESTClient()
}

// WrappedAuthenticationV1beta1 contains the wrapped logical cluster and interface.
func (w *WrappedAuthenticationV1beta1) TokenReviews() authenticationv1beta1.TokenReviewInterface {
	return &wrappedTokenReview{
		cluster:  w.cluster,
		delegate: w.delegate.TokenReviews(),
	}
}

type wrappedTokenReview struct {
	cluster  logicalcluster.Name
	delegate authenticationv1beta1.TokenReviewInterface
}

// checkCluster retrieves the logical cluster name from the given context and checks
// if it is the same as the one passed while creating a wrappedTokenReview. It errors when
// there is a mismatch.
func (w *wrappedTokenReview) checkCluster(ctx context.Context) (context.Context, error) {
	ctxCluster, ok := kcp.ClusterFromContext(ctx)
	if !ok {
		return kcp.WithCluster(ctx, w.cluster), nil
	} else if ctxCluster != w.cluster {
		return ctx, fmt.Errorf("cluster mismatch: context=%q, client=%q", ctxCluster, w.cluster)
	}
	return ctx, nil
}

// Create implements TokenReviewInterface.
func (w *wrappedTokenReview) Create(ctx context.Context, tokenReview *authenticationapiv1beta1.TokenReview, opts metav1.CreateOptions) (*authenticationapiv1beta1.TokenReview, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Create(ctx, tokenReview, opts)
}
