//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright YEAR The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1beta1

import (
	"context"
	"fmt"
	kcp "github.com/kcp-dev/apimachinery/pkg/client"
	"github.com/kcp-dev/logicalcluster"
	batchapiv1beta1 "k8s.io/api/batch/v1beta1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	batchapplyv1beta1 "k8s.io/client-go/applyconfigurations/batch/v1beta1"
	batchv1beta1 "k8s.io/client-go/kubernetes/typed/batch/v1beta1"
	"k8s.io/client-go/rest"
)

// WrappedBatchV1beta1 wraps the client interface with a
// logical cluster.
type WrappedBatchV1beta1 struct {
	cluster  logicalcluster.Name
	delegate batchv1beta1.BatchV1beta1Interface
}

// New creates a WrappedBatchV1beta1 with the given logical cluster and client interface.
func New(cluster logicalcluster.Name, delegate batchv1beta1.BatchV1beta1Interface) *WrappedBatchV1beta1 {
	return &WrappedBatchV1beta1{cluster: cluster, delegate: delegate}
}

// RESTClient returns the underlying RESTClient.
func (w *WrappedBatchV1beta1) RESTClient() rest.Interface {
	return w.delegate.RESTClient()
}

// WrappedBatchV1beta1 contains the wrapped logical cluster and interface.
func (w *WrappedBatchV1beta1) CronJobs(namespace string) batchv1beta1.CronJobInterface {
	return &wrappedCronJob{
		cluster:  w.cluster,
		delegate: w.delegate.CronJobs(namespace),
	}
}

type wrappedCronJob struct {
	cluster  logicalcluster.Name
	delegate batchv1beta1.CronJobInterface
}

// checkCluster retrieves the logical cluster name from the given context and checks
// if it is the same as the one passed while creating a wrappedCronJob. It errors when
// there is a mismatch.
func (w *wrappedCronJob) checkCluster(ctx context.Context) (context.Context, error) {
	ctxCluster, ok := kcp.ClusterFromContext(ctx)
	if !ok {
		return kcp.WithCluster(ctx, w.cluster), nil
	} else if ctxCluster != w.cluster {
		return ctx, fmt.Errorf("cluster mismatch: context=%q, client=%q", ctxCluster, w.cluster)
	}
	return ctx, nil
}

// Get implements CronJobInterface.
func (w *wrappedCronJob) Get(ctx context.Context, name string, opts metav1.GetOptions) (*batchapiv1beta1.CronJob, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Get(ctx, name, opts)
}

// List implements CronJobInterface.
func (w *wrappedCronJob) List(ctx context.Context, opts metav1.ListOptions) (*batchapiv1beta1.CronJobList, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.List(ctx, opts)
}

// Watch implements CronJobInterface.
func (w *wrappedCronJob) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Watch(ctx, opts)
}

// Create implements CronJobInterface.
func (w *wrappedCronJob) Create(ctx context.Context, cronJob *batchapiv1beta1.CronJob, opts metav1.CreateOptions) (*batchapiv1beta1.CronJob, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Create(ctx, cronJob, opts)
}

// Update implements CronJobInterface.
func (w *wrappedCronJob) Update(ctx context.Context, cronJob *batchapiv1beta1.CronJob, opts metav1.UpdateOptions) (*batchapiv1beta1.CronJob, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Update(ctx, cronJob, opts)
}

// UpdateStatus implements CronJobInterface. It was generated because the type contains a Status member.
func (w *wrappedCronJob) UpdateStatus(ctx context.Context, cronJob *batchapiv1beta1.CronJob, opts metav1.UpdateOptions) (*batchapiv1beta1.CronJob, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.UpdateStatus(ctx, cronJob, opts)
}

// Delete implements CronJobInterface.
func (w *wrappedCronJob) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return err
	}
	return w.delegate.Delete(ctx, name, opts)
}

// DeleteCollection implements CronJobInterface.
func (w *wrappedCronJob) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listopts metav1.ListOptions) error {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return err
	}
	return w.delegate.DeleteCollection(ctx, opts, listopts)
}

// Patch implements CronJobInterface.
func (w *wrappedCronJob) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *batchapiv1beta1.CronJob, err error) {
	ctx, err = w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Patch(ctx, name, pt, data, opts, subresources...)
}

// Apply implements CronJobInterface.
func (w *wrappedCronJob) Apply(ctx context.Context, cronJob *batchapplyv1beta1.CronJobApplyConfiguration, opts metav1.ApplyOptions) (result *batchapiv1beta1.CronJob, err error) {
	ctx, err = w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Apply(ctx, cronJob, opts)
}

// ApplyStatus implements CronJobInterface.
func (w *wrappedCronJob) ApplyStatus(ctx context.Context, cronJob *batchapplyv1beta1.CronJobApplyConfiguration, opts metav1.ApplyOptions) (result *batchapiv1beta1.CronJob, err error) {
	ctx, err = w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.ApplyStatus(ctx, cronJob, opts)
}
