//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright YEAR The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1

import (
	"context"
	"fmt"
	kcp "github.com/kcp-dev/apimachinery/pkg/client"
	"github.com/kcp-dev/logicalcluster"
	eventsapiv1 "k8s.io/api/events/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	eventsapplyv1 "k8s.io/client-go/applyconfigurations/events/v1"
	eventsv1 "k8s.io/client-go/kubernetes/typed/events/v1"
	"k8s.io/client-go/rest"
)

// WrappedEventsV1 wraps the client interface with a
// logical cluster.
type WrappedEventsV1 struct {
	cluster  logicalcluster.Name
	delegate eventsv1.EventsV1Interface
}

// New creates a WrappedEventsV1 with the given logical cluster and client interface.
func New(cluster logicalcluster.Name, delegate eventsv1.EventsV1Interface) *WrappedEventsV1 {
	return &WrappedEventsV1{cluster: cluster, delegate: delegate}
}

// RESTClient returns the underlying RESTClient.
func (w *WrappedEventsV1) RESTClient() rest.Interface {
	return w.delegate.RESTClient()
}

// WrappedEventsV1 contains the wrapped logical cluster and interface.
func (w *WrappedEventsV1) Events(namespace string) eventsv1.EventInterface {
	return &wrappedEvent{
		cluster:  w.cluster,
		delegate: w.delegate.Events(namespace),
	}
}

type wrappedEvent struct {
	cluster  logicalcluster.Name
	delegate eventsv1.EventInterface
}

// checkCluster retrieves the logical cluster name from the given context and checks
// if it is the same as the one passed while creating a wrappedEvent. It errors when
// there is a mismatch.
func (w *wrappedEvent) checkCluster(ctx context.Context) (context.Context, error) {
	ctxCluster, ok := kcp.ClusterFromContext(ctx)
	if !ok {
		return kcp.WithCluster(ctx, w.cluster), nil
	} else if ctxCluster != w.cluster {
		return ctx, fmt.Errorf("cluster mismatch: context=%q, client=%q", ctxCluster, w.cluster)
	}
	return ctx, nil
}

// Get implements EventInterface.
func (w *wrappedEvent) Get(ctx context.Context, name string, opts metav1.GetOptions) (*eventsapiv1.Event, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Get(ctx, name, opts)
}

// List implements EventInterface.
func (w *wrappedEvent) List(ctx context.Context, opts metav1.ListOptions) (*eventsapiv1.EventList, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.List(ctx, opts)
}

// Watch implements EventInterface.
func (w *wrappedEvent) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Watch(ctx, opts)
}

// Create implements EventInterface.
func (w *wrappedEvent) Create(ctx context.Context, event *eventsapiv1.Event, opts metav1.CreateOptions) (*eventsapiv1.Event, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Create(ctx, event, opts)
}

// Update implements EventInterface.
func (w *wrappedEvent) Update(ctx context.Context, event *eventsapiv1.Event, opts metav1.UpdateOptions) (*eventsapiv1.Event, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Update(ctx, event, opts)
}

// Delete implements EventInterface.
func (w *wrappedEvent) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return err
	}
	return w.delegate.Delete(ctx, name, opts)
}

// DeleteCollection implements EventInterface.
func (w *wrappedEvent) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listopts metav1.ListOptions) error {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return err
	}
	return w.delegate.DeleteCollection(ctx, opts, listopts)
}

// Patch implements EventInterface.
func (w *wrappedEvent) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *eventsapiv1.Event, err error) {
	ctx, err = w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Patch(ctx, name, pt, data, opts, subresources...)
}

// Apply implements EventInterface.
func (w *wrappedEvent) Apply(ctx context.Context, event *eventsapplyv1.EventApplyConfiguration, opts metav1.ApplyOptions) (result *eventsapiv1.Event, err error) {
	ctx, err = w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Apply(ctx, event, opts)
}
