//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright YEAR The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1

import (
	"context"
	"fmt"
	kcp "github.com/kcp-dev/apimachinery/pkg/client"
	"github.com/kcp-dev/logicalcluster"
	certificatesapiv1 "k8s.io/api/certificates/v1"
	certificatesigningrequestapi "k8s.io/api/certificates/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	certificatesapplyv1 "k8s.io/client-go/applyconfigurations/certificates/v1"
	certificatesv1 "k8s.io/client-go/kubernetes/typed/certificates/v1"
	"k8s.io/client-go/rest"
)

// WrappedCertificatesV1 wraps the client interface with a
// logical cluster.
type WrappedCertificatesV1 struct {
	cluster  logicalcluster.Name
	delegate certificatesv1.CertificatesV1Interface
}

// New creates a WrappedCertificatesV1 with the given logical cluster and client interface.
func New(cluster logicalcluster.Name, delegate certificatesv1.CertificatesV1Interface) *WrappedCertificatesV1 {
	return &WrappedCertificatesV1{cluster: cluster, delegate: delegate}
}

// RESTClient returns the underlying RESTClient.
func (w *WrappedCertificatesV1) RESTClient() rest.Interface {
	return w.delegate.RESTClient()
}

// WrappedCertificatesV1 contains the wrapped logical cluster and interface.
func (w *WrappedCertificatesV1) CertificateSigningRequests() certificatesv1.CertificateSigningRequestInterface {
	return &wrappedCertificateSigningRequest{
		cluster:  w.cluster,
		delegate: w.delegate.CertificateSigningRequests(),
	}
}

type wrappedCertificateSigningRequest struct {
	cluster  logicalcluster.Name
	delegate certificatesv1.CertificateSigningRequestInterface
}

// checkCluster retrieves the logical cluster name from the given context and checks
// if it is the same as the one passed while creating a wrappedCertificateSigningRequest. It errors when
// there is a mismatch.
func (w *wrappedCertificateSigningRequest) checkCluster(ctx context.Context) (context.Context, error) {
	ctxCluster, ok := kcp.ClusterFromContext(ctx)
	if !ok {
		return kcp.WithCluster(ctx, w.cluster), nil
	} else if ctxCluster != w.cluster {
		return ctx, fmt.Errorf("cluster mismatch: context=%q, client=%q", ctxCluster, w.cluster)
	}
	return ctx, nil
}

// Get implements CertificateSigningRequestInterface.
func (w *wrappedCertificateSigningRequest) Get(ctx context.Context, name string, opts metav1.GetOptions) (*certificatesapiv1.CertificateSigningRequest, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Get(ctx, name, opts)
}

// List implements CertificateSigningRequestInterface.
func (w *wrappedCertificateSigningRequest) List(ctx context.Context, opts metav1.ListOptions) (*certificatesapiv1.CertificateSigningRequestList, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.List(ctx, opts)
}

// Watch implements CertificateSigningRequestInterface.
func (w *wrappedCertificateSigningRequest) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Watch(ctx, opts)
}

// Create implements CertificateSigningRequestInterface.
func (w *wrappedCertificateSigningRequest) Create(ctx context.Context, certificateSigningRequest *certificatesapiv1.CertificateSigningRequest, opts metav1.CreateOptions) (*certificatesapiv1.CertificateSigningRequest, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Create(ctx, certificateSigningRequest, opts)
}

// Update implements CertificateSigningRequestInterface.
func (w *wrappedCertificateSigningRequest) Update(ctx context.Context, certificateSigningRequest *certificatesapiv1.CertificateSigningRequest, opts metav1.UpdateOptions) (*certificatesapiv1.CertificateSigningRequest, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Update(ctx, certificateSigningRequest, opts)
}

// UpdateStatus implements CertificateSigningRequestInterface. It was generated because the type contains a Status member.
func (w *wrappedCertificateSigningRequest) UpdateStatus(ctx context.Context, certificateSigningRequest *certificatesapiv1.CertificateSigningRequest, opts metav1.UpdateOptions) (*certificatesapiv1.CertificateSigningRequest, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.UpdateStatus(ctx, certificateSigningRequest, opts)
}

// Delete implements CertificateSigningRequestInterface.
func (w *wrappedCertificateSigningRequest) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return err
	}
	return w.delegate.Delete(ctx, name, opts)
}

// DeleteCollection implements CertificateSigningRequestInterface.
func (w *wrappedCertificateSigningRequest) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listopts metav1.ListOptions) error {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return err
	}
	return w.delegate.DeleteCollection(ctx, opts, listopts)
}

// Patch implements CertificateSigningRequestInterface.
func (w *wrappedCertificateSigningRequest) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *certificatesapiv1.CertificateSigningRequest, err error) {
	ctx, err = w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Patch(ctx, name, pt, data, opts, subresources...)
}

// Apply implements CertificateSigningRequestInterface.
func (w *wrappedCertificateSigningRequest) Apply(ctx context.Context, certificateSigningRequest *certificatesapplyv1.CertificateSigningRequestApplyConfiguration, opts metav1.ApplyOptions) (result *certificatesapiv1.CertificateSigningRequest, err error) {
	ctx, err = w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Apply(ctx, certificateSigningRequest, opts)
}

// ApplyStatus implements CertificateSigningRequestInterface.
func (w *wrappedCertificateSigningRequest) ApplyStatus(ctx context.Context, certificateSigningRequest *certificatesapplyv1.CertificateSigningRequestApplyConfiguration, opts metav1.ApplyOptions) (result *certificatesapiv1.CertificateSigningRequest, err error) {
	ctx, err = w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.ApplyStatus(ctx, certificateSigningRequest, opts)
}

// UpdateApproval implements CertificateSigningRequestInterface.
func (w *wrappedCertificateSigningRequest) UpdateApproval(ctx context.Context, name string, certificatesigningrequest *certificatesigningrequestapi.CertificateSigningRequest, opts metav1.UpdateOptions) (*certificatesigningrequestapi.CertificateSigningRequest, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.UpdateApproval(ctx, name, certificatesigningrequest, opts)
}
