//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright YEAR The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1

import (
	"context"
	"fmt"
	kcp "github.com/kcp-dev/apimachinery/pkg/client"
	"github.com/kcp-dev/logicalcluster"
	coordinationapiv1 "k8s.io/api/coordination/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	coordinationapplyv1 "k8s.io/client-go/applyconfigurations/coordination/v1"
	coordinationv1 "k8s.io/client-go/kubernetes/typed/coordination/v1"
	"k8s.io/client-go/rest"
)

// WrappedCoordinationV1 wraps the client interface with a
// logical cluster.
type WrappedCoordinationV1 struct {
	cluster  logicalcluster.Name
	delegate coordinationv1.CoordinationV1Interface
}

// New creates a WrappedCoordinationV1 with the given logical cluster and client interface.
func New(cluster logicalcluster.Name, delegate coordinationv1.CoordinationV1Interface) *WrappedCoordinationV1 {
	return &WrappedCoordinationV1{cluster: cluster, delegate: delegate}
}

// RESTClient returns the underlying RESTClient.
func (w *WrappedCoordinationV1) RESTClient() rest.Interface {
	return w.delegate.RESTClient()
}

// WrappedCoordinationV1 contains the wrapped logical cluster and interface.
func (w *WrappedCoordinationV1) Leases(namespace string) coordinationv1.LeaseInterface {
	return &wrappedLease{
		cluster:  w.cluster,
		delegate: w.delegate.Leases(namespace),
	}
}

type wrappedLease struct {
	cluster  logicalcluster.Name
	delegate coordinationv1.LeaseInterface
}

// checkCluster retrieves the logical cluster name from the given context and checks
// if it is the same as the one passed while creating a wrappedLease. It errors when
// there is a mismatch.
func (w *wrappedLease) checkCluster(ctx context.Context) (context.Context, error) {
	ctxCluster, ok := kcp.ClusterFromContext(ctx)
	if !ok {
		return kcp.WithCluster(ctx, w.cluster), nil
	} else if ctxCluster != w.cluster {
		return ctx, fmt.Errorf("cluster mismatch: context=%q, client=%q", ctxCluster, w.cluster)
	}
	return ctx, nil
}

// Get implements LeaseInterface.
func (w *wrappedLease) Get(ctx context.Context, name string, opts metav1.GetOptions) (*coordinationapiv1.Lease, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Get(ctx, name, opts)
}

// List implements LeaseInterface.
func (w *wrappedLease) List(ctx context.Context, opts metav1.ListOptions) (*coordinationapiv1.LeaseList, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.List(ctx, opts)
}

// Watch implements LeaseInterface.
func (w *wrappedLease) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Watch(ctx, opts)
}

// Create implements LeaseInterface.
func (w *wrappedLease) Create(ctx context.Context, lease *coordinationapiv1.Lease, opts metav1.CreateOptions) (*coordinationapiv1.Lease, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Create(ctx, lease, opts)
}

// Update implements LeaseInterface.
func (w *wrappedLease) Update(ctx context.Context, lease *coordinationapiv1.Lease, opts metav1.UpdateOptions) (*coordinationapiv1.Lease, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Update(ctx, lease, opts)
}

// Delete implements LeaseInterface.
func (w *wrappedLease) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return err
	}
	return w.delegate.Delete(ctx, name, opts)
}

// DeleteCollection implements LeaseInterface.
func (w *wrappedLease) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listopts metav1.ListOptions) error {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return err
	}
	return w.delegate.DeleteCollection(ctx, opts, listopts)
}

// Patch implements LeaseInterface.
func (w *wrappedLease) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *coordinationapiv1.Lease, err error) {
	ctx, err = w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Patch(ctx, name, pt, data, opts, subresources...)
}

// Apply implements LeaseInterface.
func (w *wrappedLease) Apply(ctx context.Context, lease *coordinationapplyv1.LeaseApplyConfiguration, opts metav1.ApplyOptions) (result *coordinationapiv1.Lease, err error) {
	ctx, err = w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Apply(ctx, lease, opts)
}
