//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright YEAR The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"fmt"
	kcp "github.com/kcp-dev/apimachinery/pkg/client"
	"github.com/kcp-dev/logicalcluster"
	imagepolicyapiv1alpha1 "k8s.io/api/imagepolicy/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	imagepolicyv1alpha1 "k8s.io/client-go/kubernetes/typed/imagepolicy/v1alpha1"
	"k8s.io/client-go/rest"
)

// WrappedImagepolicyV1alpha1 wraps the client interface with a
// logical cluster.
type WrappedImagepolicyV1alpha1 struct {
	cluster  logicalcluster.Name
	delegate imagepolicyv1alpha1.ImagepolicyV1alpha1Interface
}

// New creates a WrappedImagepolicyV1alpha1 with the given logical cluster and client interface.
func New(cluster logicalcluster.Name, delegate imagepolicyv1alpha1.ImagepolicyV1alpha1Interface) *WrappedImagepolicyV1alpha1 {
	return &WrappedImagepolicyV1alpha1{cluster: cluster, delegate: delegate}
}

// RESTClient returns the underlying RESTClient.
func (w *WrappedImagepolicyV1alpha1) RESTClient() rest.Interface {
	return w.delegate.RESTClient()
}

// WrappedImagepolicyV1alpha1 contains the wrapped logical cluster and interface.
func (w *WrappedImagepolicyV1alpha1) ImageReviews() imagepolicyv1alpha1.ImageReviewInterface {
	return &wrappedImageReview{
		cluster:  w.cluster,
		delegate: w.delegate.ImageReviews(),
	}
}

type wrappedImageReview struct {
	cluster  logicalcluster.Name
	delegate imagepolicyv1alpha1.ImageReviewInterface
}

// checkCluster retrieves the logical cluster name from the given context and checks
// if it is the same as the one passed while creating a wrappedImageReview. It errors when
// there is a mismatch.
func (w *wrappedImageReview) checkCluster(ctx context.Context) (context.Context, error) {
	ctxCluster, ok := kcp.ClusterFromContext(ctx)
	if !ok {
		return kcp.WithCluster(ctx, w.cluster), nil
	} else if ctxCluster != w.cluster {
		return ctx, fmt.Errorf("cluster mismatch: context=%q, client=%q", ctxCluster, w.cluster)
	}
	return ctx, nil
}
