//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright YEAR The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code auto-generated. DO NOT EDIT.

package v1

import (
	"context"
	"fmt"
	autoscalingapiv1 "k8s.io/api/autoscaling/v1"
	autoscalingv1 "k8s.io/client-go/kubernetes/typed/autoscaling/v1"

	kcp "github.com/kcp-dev/apimachinery/pkg/client"
	"github.com/kcp-dev/apimachinery/pkg/logicalcluster"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/rest"
)

type WrappedAutoscalingV1 struct {
	Cluster  logicalcluster.LogicalCluster
	Delegate autoscalingv1.AutoscalingV1Interface
}

func (w *WrappedAutoscalingV1) RESTClient() rest.Interface {
	return w.Delegate.RESTClient()
}

func (w *WrappedAutoscalingV1) HorizontalPodAutoscalers(namespace string) autoscalingv1.HorizontalPodAutoscalerInterface {
	return &wrappedHorizontalPodAutoscaler{
		cluster:  w.Cluster,
		delegate: w.Delegate.HorizontalPodAutoscalers(namespace),
	}
}

type wrappedHorizontalPodAutoscaler struct {
	cluster  logicalcluster.LogicalCluster
	delegate autoscalingv1.HorizontalPodAutoscalerInterface
}

func (w *wrappedHorizontalPodAutoscaler) checkCluster(ctx context.Context) (context.Context, error) {
	ctxCluster, ok := kcp.ClusterFromContext(ctx)
	if !ok {
		return kcp.WithCluster(ctx, w.cluster), nil
	} else if ctxCluster != w.cluster {
		return ctx, fmt.Errorf("cluster mismatch: context=%q, client=%q", ctxCluster, w.cluster)
	}
	return ctx, nil
}

func (w *wrappedHorizontalPodAutoscaler) Create(ctx context.Context, horizontalPodAutoscaler *autoscalingapiv1.HorizontalPodAutoscaler, opts metav1.CreateOptions) (*autoscalingapiv1.HorizontalPodAutoscaler, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Create(ctx, horizontalPodAutoscaler, opts)
}

func (w *wrappedHorizontalPodAutoscaler) Update(ctx context.Context, horizontalPodAutoscaler *autoscalingapiv1.HorizontalPodAutoscaler, opts metav1.UpdateOptions) (*autoscalingapiv1.HorizontalPodAutoscaler, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Update(ctx, horizontalPodAutoscaler, opts)
}

func (w *wrappedHorizontalPodAutoscaler) UpdateStatus(ctx context.Context, horizontalPodAutoscaler *autoscalingapiv1.HorizontalPodAutoscaler, opts metav1.UpdateOptions) (*autoscalingapiv1.HorizontalPodAutoscaler, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.UpdateStatus(ctx, horizontalPodAutoscaler, opts)
}

func (w *wrappedHorizontalPodAutoscaler) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return err
	}
	return w.delegate.Delete(ctx, name, opts)
}

func (w *wrappedHorizontalPodAutoscaler) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listopts metav1.ListOptions) error {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return err
	}
	return w.delegate.DeleteCollection(ctx, opts, listopts)
}

func (w *wrappedHorizontalPodAutoscaler) Get(ctx context.Context, name string, opts metav1.GetOptions) (*autoscalingapiv1.HorizontalPodAutoscaler, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Get(ctx, name, opts)
}

func (w *wrappedHorizontalPodAutoscaler) List(ctx context.Context, opts metav1.ListOptions) (*autoscalingapiv1.HorizontalPodAutoscalerList, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.List(ctx, opts)
}

func (w *wrappedHorizontalPodAutoscaler) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Watch(ctx, opts)
}

func (w *wrappedHorizontalPodAutoscaler) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *autoscalingapiv1.HorizontalPodAutoscaler, err error) {
	ctx, err = w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Patch(ctx, name, pt, data, opts, subresources...)
}
