//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright YEAR The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1beta1

import (
	"context"
	"fmt"
	kcp "github.com/kcp-dev/apimachinery/pkg/client"
	"github.com/kcp-dev/logicalcluster"
	nodeapiv1beta1 "k8s.io/api/node/v1beta1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	nodeapplyv1beta1 "k8s.io/client-go/applyconfigurations/node/v1beta1"
	nodev1beta1 "k8s.io/client-go/kubernetes/typed/node/v1beta1"
	"k8s.io/client-go/rest"
)

// WrappedNodeV1beta1 wraps the client interface with a
// logical cluster.
type WrappedNodeV1beta1 struct {
	cluster  logicalcluster.Name
	delegate nodev1beta1.NodeV1beta1Interface
}

// New creates a WrappedNodeV1beta1 with the given logical cluster and client interface.
func New(cluster logicalcluster.Name, delegate nodev1beta1.NodeV1beta1Interface) *WrappedNodeV1beta1 {
	return &WrappedNodeV1beta1{cluster: cluster, delegate: delegate}
}

// RESTClient returns the underlying RESTClient.
func (w *WrappedNodeV1beta1) RESTClient() rest.Interface {
	return w.delegate.RESTClient()
}

// WrappedNodeV1beta1 contains the wrapped logical cluster and interface.
func (w *WrappedNodeV1beta1) RuntimeClasses() nodev1beta1.RuntimeClassInterface {
	return &wrappedRuntimeClass{
		cluster:  w.cluster,
		delegate: w.delegate.RuntimeClasses(),
	}
}

type wrappedRuntimeClass struct {
	cluster  logicalcluster.Name
	delegate nodev1beta1.RuntimeClassInterface
}

// checkCluster retrieves the logical cluster name from the given context and checks
// if it is the same as the one passed while creating a wrappedRuntimeClass. It errors when
// there is a mismatch.
func (w *wrappedRuntimeClass) checkCluster(ctx context.Context) (context.Context, error) {
	ctxCluster, ok := kcp.ClusterFromContext(ctx)
	if !ok {
		return kcp.WithCluster(ctx, w.cluster), nil
	} else if ctxCluster != w.cluster {
		return ctx, fmt.Errorf("cluster mismatch: context=%q, client=%q", ctxCluster, w.cluster)
	}
	return ctx, nil
}

// Get implements RuntimeClassInterface.
func (w *wrappedRuntimeClass) Get(ctx context.Context, name string, opts metav1.GetOptions) (*nodeapiv1beta1.RuntimeClass, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Get(ctx, name, opts)
}

// List implements RuntimeClassInterface.
func (w *wrappedRuntimeClass) List(ctx context.Context, opts metav1.ListOptions) (*nodeapiv1beta1.RuntimeClassList, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.List(ctx, opts)
}

// Watch implements RuntimeClassInterface.
func (w *wrappedRuntimeClass) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Watch(ctx, opts)
}

// Create implements RuntimeClassInterface.
func (w *wrappedRuntimeClass) Create(ctx context.Context, runtimeClass *nodeapiv1beta1.RuntimeClass, opts metav1.CreateOptions) (*nodeapiv1beta1.RuntimeClass, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Create(ctx, runtimeClass, opts)
}

// Update implements RuntimeClassInterface.
func (w *wrappedRuntimeClass) Update(ctx context.Context, runtimeClass *nodeapiv1beta1.RuntimeClass, opts metav1.UpdateOptions) (*nodeapiv1beta1.RuntimeClass, error) {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Update(ctx, runtimeClass, opts)
}

// Delete implements RuntimeClassInterface.
func (w *wrappedRuntimeClass) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return err
	}
	return w.delegate.Delete(ctx, name, opts)
}

// DeleteCollection implements RuntimeClassInterface.
func (w *wrappedRuntimeClass) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listopts metav1.ListOptions) error {
	ctx, err := w.checkCluster(ctx)
	if err != nil {
		return err
	}
	return w.delegate.DeleteCollection(ctx, opts, listopts)
}

// Patch implements RuntimeClassInterface.
func (w *wrappedRuntimeClass) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *nodeapiv1beta1.RuntimeClass, err error) {
	ctx, err = w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Patch(ctx, name, pt, data, opts, subresources...)
}

// Apply implements RuntimeClassInterface.
func (w *wrappedRuntimeClass) Apply(ctx context.Context, runtimeClass *nodeapplyv1beta1.RuntimeClassApplyConfiguration, opts metav1.ApplyOptions) (result *nodeapiv1beta1.RuntimeClass, err error) {
	ctx, err = w.checkCluster(ctx)
	if err != nil {
		return nil, err
	}
	return w.delegate.Apply(ctx, runtimeClass, opts)
}
